CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS Model (
    id SERIAL,
    ModelID UUID DEFAULT gen_random_uuid() PRIMARY KEY NOT NULL,
    Name TEXT,
    aabb JSONB,
    LastModifiedTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ModelItem (
	ID SERIAL,
	ModelItemID UUID DEFAULT gen_random_uuid() PRIMARY KEY NOT NULL,
	DisplayName TEXT,
	HierachyIndex INT,
	Path TEXT DEFAULT NULL,
	Color JSONB DEFAULT NULL,
	Mesh JSONB DEFAULT NULL,
	Matrix REAL[] DEFAULT NULL,
	aabb BOX3D DEFAULT NULL,
    Properties JSONB DEFAULT NULL,
	LastModifiedTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ModelID UUID REFERENCES Model(ModelID) NOT NULL,
    BatchedModelItemID UUID REFERENCES ModelItem(ModelItemID) DEFAULT NULL
);